resolver: lts-3.0
extra-deps:
- ignore-0.1.1.0
flags:
  ignore:
    without-pcre: true
image:
  container:
    base: "fpco/ubuntu-with-libgmp:14.04"
    add:
      man/: /usr/local/share/man/
    entrypoints:
      - stack
