resolver: lts-5.15
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- hpack-0.14.0
- path-io-1.1.0
- th-lift-instances-0.1.6
- th-reify-many-0.1.6
- th-utilities-0.1.0.1
- store-0.1.0.0
- th-orphans-0.13.1
packages:
- .
- location: ../store
  extra-dep: true
