resolver: lts-10.5
packages:
- .
- subs/rio

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
# https://github.com/commercialhaskell/stack/issues/3785
- ansi-terminal-0.8.0.2@rev:0
- archive: https://github.com/haskell/hackage-security/archive/3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7.tar.gz
  subdirs:
  - hackage-security
- Cabal-2.2.0.0@rev:1
- cabal-doctest-1.0.6@rev:1

# https://github.com/fizruk/http-api-data/issues/72
- archive: https://github.com/snoyberg/http-api-data/archive/659dc4689355a5881acc2e037090d75391c673bb.tar.gz
