resolver: lts-5.3
image:
  containers:
    - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
      name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- hpack-0.12.0
- path-0.5.7
- path-io-1.1.0
- tls-1.3.5
- cryptonite-0.15 # for tls-1.3.5
